### ISSUE TITLE
i have some questions ......

### ISSUE THREAD

**Issue by snikeguo** [NETMF/Llvm.NET#12]
Hello! I come from Shenzhen, China. Glad to see this project. I have some questions to ask.
1.Intermediate, Signed, Unsigned. I see there are LibLLVM.DLL, Llvm.NET.DLL. What is the difference between these folders?
2 I am an embedded Engineer (ARM Cortex-M0+/M3/M4 Engineer). I want a LLVM based C# compiler. You can generate the HEX/ELF file by entering the source code files and the link script file. This function can be achieved? Because I don't understand LLVM, I need a EXE program. Achieve "CS files ------->elf file" function. Please help me. Thank you.
3 to provide the necessary libraries, such as" System.Convert class, string class, List<> class " etc..
4 if the microcontroller project without RTOS, then how to deal with GC? Because the microcontroller project with RTOS words, you can put GC into the IDLE thread.
Finally, I hope you come to China to play.   ( ^_^ )

**Comment by smaillet-ms** [comment]
@snikeguo 
1.  LibLLVM is an unmanaged DLL that provides an extended C API for LLVM.  This includes all the official LLVM-C APIs and a significant set of extensions to support use of LLVM from other languages and runtimes such as .NET. Llvm.NET is a .NET library that uses LibLLVM to provide a .NET object model for accessing LLVM libraries from .NET applications. These are building blocks for using LLVM from .NET applications. 
2. Great, this is part of why Llvm.NET was created. The LLilum project uses LLVM.NET to convert .NET code for embedded targets. It is a complicated code base with a long history and, while functional, is slow to generate the target code and also has a large run-time footprint. Which, is why I have been working on a new set of tools and updating LLVM.NET. Once the holidays are over in the US I should have all the "paperwork" done with the .NET Foundation so I can publish the first stages of that project. There's a lot of work yet to be done but, so far things are looking good.
3. Runtime-libraries will, of course, be required for any new run-time or tooling. Fortunately the idea of cross platform .NET applications has hit mainstream and projects like .NET Core and the .NET Standard Library help in establishing the patterns and techniques for dealing with OS or Runtime specific implementation variations. They also provide OSS implementations of those libraries that we can leverage.
4. Multiple options exist for handling GC, including not having any at all. For the majority of embedded devices the conservative Boehm collector is likely more than adequate. If there is no idle thread for collection then a collector could be run sequentially as part of the heap allocation. (e.g. when allocating memory and the heap has reached some pre-determined limit, run  a collection to free up memory...) Lot's of options there and I don't think that a single "one size fits all" solution is plausible, let alone desirable.

**Comment by snikeguo** [comment]
I know the llilum project, it hasn't been updated for a long time.
i will continue to pay attention to LLVM.NET project.
OK ,. Look forward to publishing project! 
 ( ^_^ )

**Comment by snikeguo** [comment]
@smaillet-ms 
I know the llilum project, it hasn't been updated for a long time.
i will continue to pay attention to LLVM.NET project.
OK ,. Look forward to publishing project! 
 ( ^_^ )
